// trip-web-frontend/app/components/ui/Card.vue
<script setup lang="ts">
import { cn } from '~/utils'

interface Props {
  class?: string
  padding?: 'none' | 'sm' | 'md' | 'lg'
  hover?: boolean
  clickable?: boolean
}

const props = withDefaults(defineProps<Props>(), {
  padding: 'md',
  hover: false,
  clickable: false,
})

const paddingClasses = {
  none: '',
  sm: 'p-3',
  md: 'p-5',
  lg: 'p-7',
}
</script>

<template>
  <div
    :class="cn(
      'bg-white rounded-xl border border-gray-100 shadow-sm',
      paddingClasses[props.padding],
      props.hover && 'card-hover',
      props.clickable && 'cursor-pointer',
      props.class
    )"
  >
    <slot />
  </div>
</template>

// trip-next-frontend/components/ui/card.tsx
import { cn } from "@/lib/utils";
import * as React from "react";

export interface CardProps extends React.HTMLAttributes<HTMLDivElement> {
  padding?: "none" | "sm" | "md" | "lg";
  hover?: boolean;
  clickable?: boolean;
}

const paddingClasses = {
  none: "",
  sm: "p-3",
  md: "p-5",
  lg: "p-7",
};

const Card = React.forwardRef<HTMLDivElement, CardProps>(
  (
    { className, padding = "md", hover = false, clickable = false, ...props },
    ref,
  ) => (
    <div
      ref={ref}
      className={cn(
        "rounded-xl border border-gray-100 bg-white shadow-sm",
        paddingClasses[padding],
        hover && "card-hover",
        clickable && "cursor-pointer",
        className,
      )}
      {...props}
    />
  ),
);
Card.displayName = "Card";

export { Card };
