// trip-web-frontend/app/components/chat/ChatSidebar.vue
<script setup lang="ts">
import { X, Send, Sparkles, Loader2 } from 'lucide-vue-next'
import type { Message, Conversation, ChatContext } from '~/types'
import { generateId } from '~/utils'

interface Props {
  isOpen: boolean
  conversation?: Conversation | null
  initialContext?: ChatContext | null
  title?: string
}

const props = withDefaults(defineProps<Props>(), {
  isOpen: false,
  title: 'AI Assistant',
})

const emit = defineEmits<{
  close: []
  conversationCreated: [conversation: Conversation]
}>()

const auth = useAuth()
const chat = useChat()

const messages = ref<Message[]>([])
const inputMessage = ref('')
const isStreaming = ref(false)
const streamingContent = ref('')
const messagesContainer = ref<HTMLDivElement | null>(null)
const inputRef = ref<HTMLTextAreaElement | null>(null)

// Current conversation (either passed as prop or created)
const currentConversation = ref<Conversation | null>(props.conversation || null)

// Auto-scroll to bottom when new messages arrive
const scrollToBottom = () => {
  nextTick(() => {
    if (messagesContainer.value) {
      messagesContainer.value.scrollTop = messagesContainer.value.scrollHeight
    }
  })
}

// Watch for message changes
watch(messages, () => scrollToBottom(), { deep: true })
watch(streamingContent, () => scrollToBottom())

// Initialize conversation if prop changes
watch(() => props.conversation, (newConv) => {
  if (newConv) {
    currentConversation.value = newConv
    loadMessages()
  }
})

// When sidebar opens with initial context, create conversation
watch(() => props.isOpen, async (isOpen) => {
  if (isOpen && props.initialContext && !currentConversation.value) {
    await createContextualConversation()
    
    // After creating conversation, check if we need to auto-send a query
    if (props.initialContext.autoSendQuery && currentConversation.value) {
      // Wait a moment for UI to settle
      await nextTick()
      inputMessage.value = props.initialContext.autoSendQuery
      // Use autoSendMetadata if provided
      const metadata = props.initialContext.autoSendMetadata || props.initialContext
      await sendMessageWithMetadata(metadata)
    }
  }
})

// Load messages for current conversation
const loadMessages = async () => {
  if (!currentConversation.value) return
  
  const result = await chat.listMessages(
    auth.userId.value,
    currentConversation.value.conversationId
  )
  
  if (result) {
    messages.value = result.items.reverse()
  }
}

// Create a conversation with initial context
const createContextualConversation = async () => {
  if (!props.initialContext) return
  
  const conversation = await chat.createConversation(
    auth.userId.value,
    props.title,
    props.initialContext
  )
  
  if (conversation) {
    currentConversation.value = conversation
    emit('conversationCreated', conversation)
  }
}

// Create a new conversation if needed
const ensureConversation = async (): Promise<Conversation | null> => {
  if (currentConversation.value) return currentConversation.value
  
  const conversation = await chat.createConversation(
    auth.userId.value,
    props.title || 'New Chat'
  )
  
  if (conversation) {
    currentConversation.value = conversation
    emit('conversationCreated', conversation)
  }
  
  return conversation
}

// Send message handler with optional custom metadata
const sendMessageWithMetadata = async (customMetadata?: Record<string, unknown>) => {
  const content = inputMessage.value.trim()
  if (!content || isStreaming.value) return
  
  // Ensure we have a conversation
  const conversation = await ensureConversation()
  if (!conversation) return
  
  // Add user message locally
  const userMessage: Message = {
    id: generateId(),
    conversationId: conversation.conversationId,
    role: 'user',
    content,
    createdAt: new Date().toISOString(),
  }
  messages.value.push(userMessage)
  inputMessage.value = ''
  
  // Start streaming response
  isStreaming.value = true
  streamingContent.value = ''
  
  // Use custom metadata if provided, otherwise use initialContext
  const metadata = customMetadata || props.initialContext || undefined
  
  try {
    await chat.streamMessage(
      auth.userId.value,
      conversation.conversationId,
      content,
      metadata,
      // onEvent: handle ADK events (tool calls, etc.)
      (event) => {
        console.log('ADK Event:', event)
      },
      // onChunk: accumulate streaming text
      (chunk) => {
        streamingContent.value += chunk
      },
      // onMessage: handle final saved message
      (message) => {
        // Replace streaming content with final message
        streamingContent.value = ''
        messages.value.push(message)
      },
      // onComplete
      () => {
        console.log('Stream completed')
      },
      // onError
      (error) => {
        console.error('Stream error:', error)
        messages.value.push({
          id: generateId(),
          conversationId: conversation.conversationId,
          role: 'assistant',
          content: 'Sorry, I encountered an error. Please try again.',
          createdAt: new Date().toISOString(),
        })
      }
    )
  } catch (error) {
    console.error('Failed to send message:', error)
    messages.value.push({
      id: generateId(),
      conversationId: conversation.conversationId,
      role: 'assistant',
      content: 'Sorry, I encountered an error. Please try again.',
      createdAt: new Date().toISOString(),
    })
  } finally {
    isStreaming.value = false
    streamingContent.value = ''
  }
}

// Send message handler (uses default metadata from initialContext)
const sendMessage = async () => {
  await sendMessageWithMetadata()
}

// Handle enter key
const handleKeydown = (event: KeyboardEvent) => {
  if (event.key === 'Enter' && !event.shiftKey) {
    event.preventDefault()
    sendMessage()
  }
}

// Auto-resize textarea
const autoResize = (event: Event) => {
  const target = event.target as HTMLTextAreaElement
  target.style.height = 'auto'
  target.style.height = Math.min(target.scrollHeight, 120) + 'px'
}

// Reset state when closing
const handleClose = () => {
  // Reset conversation state to allow creating a new one next time
  currentConversation.value = null
  messages.value = []
  inputMessage.value = ''
  streamingContent.value = ''
  emit('close')
}

// Quick prompts for review context
const quickPrompts = computed(() => {
  if (props.initialContext?.type === 'review-summary') {
    return [
      'Summarize the reviews',
      'What do visitors like most?',
      'Any negative feedback?',
      'Best time to visit?',
    ]
  }
  return [
    'Tell me more',
    'How to get there?',
    'Nearby attractions',
    'Local tips',
  ]
})

const useQuickPrompt = (prompt: string) => {
  inputMessage.value = prompt
  sendMessage()
}
</script>

<template>
  <!-- Backdrop (only on mobile) -->
  <Transition name="fade">
    <div
      v-if="isOpen"
      class="fixed inset-0 bg-black/20 z-40 lg:hidden"
      @click="handleClose"
    />
  </Transition>

  <!-- Sidebar -->
  <Transition name="slide">
    <div
      v-if="isOpen"
      class="fixed right-0 top-16 bottom-0 w-full sm:w-[400px] lg:w-[420px] bg-white shadow-2xl z-40 flex flex-col border-l border-gray-200"
    >
      <!-- Header -->
      <div class="flex-shrink-0 flex items-center justify-between px-4 py-3 border-b border-gray-100 bg-gradient-to-r from-primary-50 to-secondary-50">
        <div class="flex items-center gap-3">
          <div class="w-9 h-9 rounded-xl bg-gradient-to-br from-primary-500 to-secondary-500 flex items-center justify-center">
            <Sparkles class="w-4 h-4 text-white" />
          </div>
          <div>
            <h2 class="font-semibold text-gray-900 text-sm">{{ title }}</h2>
            <p class="text-xs text-gray-500">AI Travel Assistant</p>
          </div>
        </div>
        <button
          class="w-8 h-8 rounded-lg hover:bg-gray-100 flex items-center justify-center text-gray-500 hover:text-gray-700 transition-colors"
          @click="handleClose"
        >
          <X class="w-5 h-5" />
        </button>
      </div>

      <!-- Messages area -->
      <div
        ref="messagesContainer"
        class="flex-1 overflow-y-auto p-4 space-y-4"
      >
        <!-- Empty state -->
        <div
          v-if="messages.length === 0 && !isStreaming"
          class="h-full flex flex-col items-center justify-center text-center px-4"
        >
          <div class="w-16 h-16 rounded-2xl bg-gradient-to-br from-primary-100 to-secondary-100 flex items-center justify-center mb-4">
            <Sparkles class="w-8 h-8 text-primary-600" />
          </div>
          <p class="text-sm text-gray-500 mb-4">
            Ask me anything about this attraction or the reviews!
          </p>
          
          <!-- Quick prompts -->
          <div class="flex flex-wrap gap-2 justify-center">
            <button
              v-for="prompt in quickPrompts"
              :key="prompt"
              class="px-3 py-1.5 text-xs bg-gray-100 hover:bg-gray-200 rounded-full text-gray-700 transition-colors"
              @click="useQuickPrompt(prompt)"
            >
              {{ prompt }}
            </button>
          </div>
        </div>

        <!-- Message list -->
        <template v-for="message in messages" :key="message.id">
          <ChatMessage :message="message" />
        </template>

        <!-- Streaming message -->
        <ChatMessage
          v-if="isStreaming"
          :message="{
            id: 'streaming',
            conversationId: currentConversation?.conversationId || '',
            role: 'assistant',
            content: streamingContent,
            createdAt: new Date().toISOString(),
          }"
          :is-streaming="true"
        />
      </div>

      <!-- Quick prompts when conversation is active -->
      <div v-if="messages.length > 0" class="flex-shrink-0 px-4 py-2 border-t border-gray-100 bg-gray-50">
        <div class="flex gap-2 overflow-x-auto pb-1">
          <button
            v-for="prompt in quickPrompts"
            :key="prompt"
            class="flex-shrink-0 px-3 py-1 text-xs bg-white border border-gray-200 hover:border-primary-300 hover:bg-primary-50 rounded-full text-gray-600 transition-colors"
            @click="useQuickPrompt(prompt)"
          >
            {{ prompt }}
          </button>
        </div>
      </div>

      <!-- Input area -->
      <div class="flex-shrink-0 p-4 border-t border-gray-100 bg-white">
        <div class="flex items-start gap-2">
          <div class="flex-1 relative">
            <textarea
              ref="inputRef"
              v-model="inputMessage"
              placeholder="Type your question..."
              class="w-full px-3 py-2.5 bg-gray-50 border border-gray-200 rounded-xl resize-none text-sm focus:outline-none focus:ring-2 focus:ring-primary-500 focus:border-transparent transition-all"
              rows="1"
              :disabled="isStreaming"
              @keydown="handleKeydown"
              @input="autoResize"
            />
          </div>
          <UiButton
            :disabled="!inputMessage.trim() || isStreaming"
            :loading="isStreaming"
            size="sm"
            class="flex-shrink-0 h-10 w-10 !p-0"
            @click="sendMessage"
          >
            <Send class="w-4 h-4" />
          </UiButton>
        </div>
      </div>
    </div>
  </Transition>
</template>

<style scoped>
.fade-enter-active,
.fade-leave-active {
  transition: opacity 0.2s ease;
}

.fade-enter-from,
.fade-leave-to {
  opacity: 0;
}

.slide-enter-active,
.slide-leave-active {
  transition: transform 0.3s ease;
}

.slide-enter-from,
.slide-leave-to {
  transform: translateX(100%);
}
</style>

// trip-next-frontend/components/chat-sidebar.tsx
"use client";

import { Button } from "@/components/ui/button";
import { useAuth } from "@/hooks/use-auth";
import { useChat } from "@/hooks/use-chat";
import { useChatSidebar } from "@/hooks/use-chat-sidebar";
import type { ChatContext, Conversation, Message } from "@/lib/types";
import { cn } from "@/lib/utils";
import { Send, Sparkles, X } from "lucide-react";
import { usePathname } from "next/navigation";
import { useEffect, useRef, useState } from "react";
import { v7 as uuidv7 } from "uuid";
import { ChatMessage } from "./chat-message";

interface ChatSidebarProps {
  conversation?: Conversation | null;
  initialContext?: ChatContext | null;
  title?: string;
  onConversationCreated?: (conversation: Conversation) => void;
}

export function ChatSidebar({
  conversation: propConversation,
  initialContext: propInitialContext,
  title: propTitle,
  onConversationCreated,
}: ChatSidebarProps) {
  const { isOpen, context, title: storeTitle, close } = useChatSidebar();
  const auth = useAuth();
  const chat = useChat();
  const pathname = usePathname();

  // Use props if provided, otherwise use store values
  const initialContext = propInitialContext || context;
  const title = propTitle || storeTitle;

  const [messages, setMessages] = useState<Message[]>([]);
  const [inputMessage, setInputMessage] = useState("");
  const [isStreaming, setIsStreaming] = useState(false);
  const [streamingContent, setStreamingContent] = useState("");
  const [currentConversation, setCurrentConversation] =
    useState<Conversation | null>(propConversation || null);

  const messagesContainerRef = useRef<HTMLDivElement>(null);
  const inputRef = useRef<HTMLTextAreaElement>(null);

  /**
   * Extract backend metadata fields from ChatContext.
   * Only includes fields that should be sent to trip-chat-service.
   */
  const extractBackendMetadata = (
    ctx: ChatContext | null,
  ): Record<string, unknown> | undefined => {
    if (!ctx) return undefined;

    const metadata: Record<string, unknown> = {};

    // Only include backend-relevant fields (snake_case convention)
    if (ctx.agent) metadata.agent = ctx.agent;
    if (ctx.target_id) metadata.target_id = ctx.target_id;
    if (ctx.target_type) metadata.target_type = ctx.target_type;

    return Object.keys(metadata).length > 0 ? metadata : undefined;
  };

  // Auto-close sidebar when navigating to /chat page
  useEffect(() => {
    if (pathname === "/chat" && isOpen) {
      close();
    }
  }, [pathname, isOpen, close]);

  // Auto-scroll to bottom when new messages arrive
  const scrollToBottom = () => {
    setTimeout(() => {
      if (messagesContainerRef.current) {
        messagesContainerRef.current.scrollTop =
          messagesContainerRef.current.scrollHeight;
      }
    }, 0);
  };

  // Scroll on message changes
  useEffect(() => {
    scrollToBottom();
  }, [messages, streamingContent]);

  // Initialize conversation if prop changes
  useEffect(() => {
    if (propConversation) {
      setCurrentConversation(propConversation);
      loadMessages();
    }
  }, [propConversation]);

  // When sidebar opens with initial context, create conversation
  useEffect(() => {
    if (isOpen && initialContext && !currentConversation) {
      createContextualConversation();
    }
  }, [isOpen, initialContext]);

  // Load messages for current conversation
  const loadMessages = async () => {
    if (!currentConversation || !auth.user) return;

    const result = await chat.listMessages(
      auth.user.id,
      currentConversation.conversationId,
    );

    if (result) {
      setMessages(result.items.reverse());
    }
  };

  // Create a conversation with initial context
  const createContextualConversation = async () => {
    if (!initialContext || !auth.user) return;

    // Extract only backend-relevant metadata for the conversation
    const backendMetadata = extractBackendMetadata(initialContext);

    const conversation = await chat.createConversation(
      auth.user.id,
      title,
      backendMetadata,
    );

    if (conversation) {
      setCurrentConversation(conversation);
      onConversationCreated?.(conversation);

      // Check if we need to auto-send a query
      if (initialContext.autoSendQuery) {
        await sendMessageWithMetadata(
          conversation,
          initialContext.autoSendQuery,
          backendMetadata,
        );
      }
    }
  };

  // Create a new conversation if needed
  const ensureConversation = async (): Promise<Conversation | null> => {
    if (currentConversation) return currentConversation;
    if (!auth.user) return null;

    const conversation = await chat.createConversation(
      auth.user.id,
      title || "New Chat",
    );

    if (conversation) {
      setCurrentConversation(conversation);
      onConversationCreated?.(conversation);
    }

    return conversation;
  };

  // Send message handler with optional custom metadata
  const sendMessageWithMetadata = async (
    conversation: Conversation,
    content: string,
    customMetadata?: Record<string, unknown>,
  ) => {
    if (!content.trim() || isStreaming || !auth.user) return;

    // Add user message locally
    const userMessage: Message = {
      id: uuidv7(),
      conversationId: conversation.conversationId,
      role: "user",
      content,
      createdAt: new Date().toISOString(),
    };
    setMessages((prev) => [...prev, userMessage]);
    setInputMessage("");

    // Start streaming response
    setIsStreaming(true);
    setStreamingContent("");

    // Use custom metadata if provided, otherwise extract from initialContext
    const metadata = customMetadata || extractBackendMetadata(initialContext);

    try {
      await chat.streamMessage(
        auth.user.id,
        conversation.conversationId,
        content,
        metadata,
        // onEvent: handle ADK events (tool calls, etc.)
        (event) => {
          console.log("ADK Event:", event);
        },
        // onChunk: accumulate streaming text
        (chunk) => {
          setStreamingContent((prev) => prev + chunk);
        },
        // onMessage: handle final saved message
        (message) => {
          // Replace streaming content with final message
          setStreamingContent("");
          setMessages((prev) => [...prev, message]);
        },
        // onComplete
        () => {
          console.log("Stream completed");
        },
        // onError
        (error) => {
          console.error("Stream error:", error);
          setMessages((prev) => [
            ...prev,
            {
              id: uuidv7(),
              conversationId: conversation.conversationId,
              role: "assistant",
              content: "Sorry, I encountered an error. Please try again.",
              createdAt: new Date().toISOString(),
            },
          ]);
        },
      );
    } catch (error) {
      console.error("Failed to send message:", error);
      setMessages((prev) => [
        ...prev,
        {
          id: uuidv7(),
          conversationId: conversation.conversationId,
          role: "assistant",
          content: "Sorry, I encountered an error. Please try again.",
          createdAt: new Date().toISOString(),
        },
      ]);
    } finally {
      setIsStreaming(false);
      setStreamingContent("");
    }
  };

  // Send message handler (uses default metadata from initialContext)
  const sendMessage = async () => {
    const content = inputMessage.trim();
    if (!content || isStreaming || !auth.user) return;

    // Ensure we have a conversation
    const conversation = await ensureConversation();
    if (!conversation) return;

    // Use the sendMessageWithMetadata function
    await sendMessageWithMetadata(conversation, content);
  };

  // Handle enter key
  const handleKeydown = (event: React.KeyboardEvent<HTMLTextAreaElement>) => {
    if (event.key === "Enter" && !event.shiftKey) {
      event.preventDefault();
      sendMessage();
    }
  };

  // Auto-resize textarea
  const autoResize = (event: React.ChangeEvent<HTMLTextAreaElement>) => {
    const target = event.target;
    target.style.height = "auto";
    target.style.height = Math.min(target.scrollHeight, 120) + "px";
  };

  // Reset state when closing
  const handleClose = () => {
    close();
  };

  // Quick prompts based on context
  const quickPrompts =
    initialContext?.type === "review-summary"
      ? [
          "Summarize the reviews",
          "What do visitors like most?",
          "Any negative feedback?",
          "Best time to visit?",
        ]
      : [
          "Tell me more",
          "How to get there?",
          "Nearby attractions",
          "Local tips",
        ];

  const handleQuickPrompt = (prompt: string) => {
    setInputMessage(prompt);
    // Send immediately
    setTimeout(() => sendMessage(), 0);
  };

  return (
    <>
      {/* Backdrop (only on mobile) */}
      <div
        className={cn(
          "fixed inset-0 z-40 bg-black/20 transition-opacity duration-200 lg:hidden",
          isOpen ? "opacity-100" : "pointer-events-none opacity-0",
        )}
        onClick={handleClose}
      />

      {/* Sidebar */}
      <div
        className={cn(
          "border-border bg-background fixed top-16 right-0 bottom-0 z-40 flex w-full flex-col border-l shadow-2xl transition-transform duration-300 ease-out sm:w-100 lg:w-105",
          isOpen ? "translate-x-0" : "translate-x-full",
        )}
      >
        {/* Header */}
        <div className="border-border bg-muted flex shrink-0 items-center justify-between border-b px-4 py-3">
          <div className="flex items-center gap-3">
            <div className="bg-primary flex h-9 w-9 items-center justify-center rounded-xl">
              <Sparkles className="text-primary-foreground h-4 w-4" />
            </div>
            <div>
              <h2 className="text-foreground text-sm font-semibold">{title}</h2>
              <p className="text-muted-foreground text-xs">
                AI Travel Assistant
              </p>
            </div>
          </div>
          <button
            className="text-muted-foreground hover:bg-muted hover:text-foreground flex h-8 w-8 items-center justify-center rounded-lg transition-colors"
            onClick={handleClose}
          >
            <X className="h-5 w-5" />
          </button>
        </div>

        {/* Messages area */}
        <div
          ref={messagesContainerRef}
          className="scrollbar-hide flex-1 space-y-4 overflow-y-auto p-4"
        >
          {/* Empty state */}
          {messages.length === 0 && !isStreaming && (
            <div className="flex h-full flex-col items-center justify-center px-4 text-center">
              <div className="bg-primary/10 mb-4 flex h-16 w-16 items-center justify-center rounded-2xl">
                <Sparkles className="text-primary h-8 w-8" />
              </div>
              <p className="text-muted-foreground mb-4 text-sm">
                Ask me anything about this attraction or the reviews!
              </p>

              {/* Quick prompts */}
              <div className="flex flex-wrap justify-center gap-2">
                {quickPrompts.map((prompt) => (
                  <button
                    key={prompt}
                    className="bg-muted text-foreground hover:bg-muted/80 rounded-full px-3 py-1.5 text-xs transition-colors"
                    onClick={() => handleQuickPrompt(prompt)}
                  >
                    {prompt}
                  </button>
                ))}
              </div>
            </div>
          )}

          {/* Message list */}
          {messages.map((message) => (
            <ChatMessage key={message.id} message={message} />
          ))}

          {/* Streaming message */}
          {isStreaming && (
            <ChatMessage
              message={{
                id: "streaming",
                conversationId: currentConversation?.conversationId || "",
                role: "assistant",
                content: streamingContent,
                createdAt: new Date().toISOString(),
              }}
              isStreaming={true}
            />
          )}
        </div>

        {/* Quick prompts when conversation is active */}
        {messages.length > 0 && (
          <div className="border-border bg-muted shrink-0 border-t px-4 py-2">
            <div className="flex gap-2 overflow-x-auto pb-1">
              {quickPrompts.map((prompt) => (
                <button
                  key={prompt}
                  className="border-border bg-background text-muted-foreground hover:border-primary/30 hover:bg-primary/5 shrink-0 rounded-full border px-3 py-1 text-xs transition-colors"
                  onClick={() => handleQuickPrompt(prompt)}
                >
                  {prompt}
                </button>
              ))}
            </div>
          </div>
        )}

        {/* Input area */}
        <div className="border-border bg-background shrink-0 border-t p-4">
          <div className="flex items-end gap-3">
            <textarea
              ref={inputRef}
              value={inputMessage}
              onChange={(e) => {
                setInputMessage(e.target.value);
                autoResize(e);
              }}
              onKeyDown={handleKeydown}
              placeholder="Type your question..."
              className="scrollbar-hide border-input bg-muted focus:ring-ring flex-1 resize-none overflow-y-auto rounded-xl border px-4 py-3 text-sm transition-all focus:border-transparent focus:ring-2 focus:outline-none"
              rows={1}
              disabled={isStreaming}
            />
            <Button
              disabled={!inputMessage.trim() || isStreaming}
              className="h-11.5 w-11.5 shrink-0 p-0!"
              onClick={sendMessage}
            >
              <Send className="h-4 w-4" />
            </Button>
          </div>
        </div>
      </div>
    </>
  );
}
