// trip-next-frontend/components/ui/avatar.tsx
import { cn, getAvatarColor, getInitials } from "@/lib/utils";
import * as AvatarPrimitive from "@radix-ui/react-avatar";
import * as React from "react";

interface AvatarProps extends React.ComponentPropsWithoutRef<
  typeof AvatarPrimitive.Root
> {
  src?: string;
  alt?: string;
  name?: string;
  size?: "xs" | "sm" | "md" | "lg" | "xl";
}

const sizeClasses = {
  xs: "w-6 h-6 text-xs",
  sm: "w-8 h-8 text-sm",
  md: "w-10 h-10 text-base",
  lg: "w-12 h-12 text-lg",
  xl: "w-16 h-16 text-xl",
};

const Avatar = React.forwardRef<
  React.ElementRef<typeof AvatarPrimitive.Root>,
  AvatarProps
>(({ className, src, alt, name, size = "md", ...props }, ref) => {
  const initials = name ? getInitials(name) : "?";
  const bgColor = name ? getAvatarColor(name) : "bg-gray-400";

  return (
    <AvatarPrimitive.Root
      ref={ref}
      className={cn(
        "relative flex items-center justify-center overflow-hidden rounded-full font-semibold text-white",
        sizeClasses[size],
        bgColor,
        className,
      )}
      {...props}
    >
      {src && (
        <AvatarPrimitive.Image
          src={src}
          alt={alt || name || "Avatar"}
          className="h-full w-full object-cover"
        />
      )}
      <AvatarPrimitive.Fallback
        className={cn(
          "flex h-full w-full items-center justify-center",
          bgColor,
        )}
      >
        {initials}
      </AvatarPrimitive.Fallback>
    </AvatarPrimitive.Root>
  );
});
Avatar.displayName = "Avatar";

export { Avatar };

// trip-web-frontend/app/components/ui/Avatar.vue
<script setup lang="ts">
import { getAvatarColor, getInitials, cn } from '~/utils'

interface Props {
  src?: string
  alt?: string
  name?: string
  size?: 'xs' | 'sm' | 'md' | 'lg' | 'xl'
  class?: string
}

const props = withDefaults(defineProps<Props>(), {
  size: 'md',
})

const sizeClasses = {
  xs: 'w-6 h-6 text-xs',
  sm: 'w-8 h-8 text-sm',
  md: 'w-10 h-10 text-base',
  lg: 'w-12 h-12 text-lg',
  xl: 'w-16 h-16 text-xl',
}

const initials = computed(() => props.name ? getInitials(props.name) : '?')
const bgColor = computed(() => props.name ? getAvatarColor(props.name) : 'bg-gray-400')
const imageError = ref(false)

const showFallback = computed(() => !props.src || imageError.value)
</script>

<template>
  <div
    :class="cn(
      'relative rounded-full overflow-hidden flex items-center justify-center font-semibold text-white',
      sizeClasses[props.size],
      showFallback && bgColor,
      props.class
    )"
  >
    <img
      v-if="props.src && !imageError"
      :src="props.src"
      :alt="props.alt || props.name || 'Avatar'"
      class="w-full h-full object-cover"
      @error="imageError = true"
    />
    <span v-else>{{ initials }}</span>
  </div>
</template>
