// trip-next-frontend/app/attractions/[id]/page.tsx
"use client";

import { ReviewForm } from "@/components/reviews/review-form";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { useAttractions } from "@/lib/hooks/use-attractions";
import { useChatSidebar } from "@/lib/hooks/use-chat-sidebar";
import type { Attraction, ChatContext, Review } from "@/lib/types";
import {
  ChevronLeft,
  Clock,
  Cloud,
  Heart,
  MapPin,
  MessageCircle,
  Share2,
  Star,
  Ticket,
} from "lucide-react";
import Link from "next/link";
import { useParams } from "next/navigation";
import { useEffect, useState } from "react";

export default function AttractionDetailPage() {
  const params = useParams();
  const attractionId = params.id as string;
  const { fetchAttraction } = useAttractions();
  const chatSidebar = useChatSidebar();

  // TODO: Replace with real authentication when user service is integrated
  const currentUser = { id: "user-1", username: "Demo User" };

  // State
  const [attraction, setAttraction] = useState<Attraction | null>(null);
  const [selectedImageIndex, setSelectedImageIndex] = useState(0);
  const [showReviewForm, setShowReviewForm] = useState(false);
  const [reviews, setReviews] = useState<Review[]>([]);
  const [reviewsLoading, setReviewsLoading] = useState(false);
  const [userReview, setUserReview] = useState<Review | null>(null);

  // Fetch attraction data
  useEffect(() => {
    const loadAttraction = async () => {
      try {
        const data = await fetchAttraction(attractionId);
        setAttraction(data);
      } catch (error) {
        console.error("Error loading attraction:", error);
      }
    };

    loadAttraction();
  }, [attractionId]);

  // Fetch reviews
  const fetchReviews = async () => {
    setReviewsLoading(true);
    try {
      // This would call the actual API
      // const response = await fetch(`${process.env.NEXT_PUBLIC_REVIEW_SERVICE_URL}/reviews?targetType=attraction&targetId=${attractionId}`)
      // For now, using mock data
      await new Promise((resolve) => setTimeout(resolve, 500));

      // Mock reviews data
      const mockReviews: Review[] = [
        {
          id: "review-1",
          userId: "user-2",
          targetType: "attraction",
          targetId: attractionId,
          rating: 5,
          text: "Absolutely stunning views, especially at night! The historic buildings are beautifully preserved and the modern skyline across the river is breathtaking.",
          images: [
            "https://images.unsplash.com/photo-1474181487882-5abf3f0ba6c2?w=400&h=300&fit=crop",
          ],
          createdAt: Date.now() - 86400000 * 2,
          updatedAt: Date.now() - 86400000 * 2,
        },
        {
          id: "review-2",
          userId: "user-3",
          targetType: "attraction",
          targetId: attractionId,
          rating: 4,
          text: "Great place for a walk along the waterfront. Very crowded during weekends and holidays though.",
          images: [],
          createdAt: Date.now() - 86400000 * 5,
          updatedAt: Date.now() - 86400000 * 5,
        },
        {
          id: "review-3",
          userId: "user-4",
          targetType: "attraction",
          targetId: attractionId,
          rating: 5,
          text: "Perfect spot for photography! Visited during sunset and the golden hour lighting was amazing.",
          images: [
            "https://images.unsplash.com/photo-1548919973-5cef591cdbc9?w=400&h=300&fit=crop",
            "https://images.unsplash.com/photo-1538428494232-9c0d8a3ab403?w=400&h=300&fit=crop",
          ],
          createdAt: Date.now() - 86400000 * 7,
          updatedAt: Date.now() - 86400000 * 7,
        },
      ];

      setReviews(mockReviews);

      // Check if current user has reviewed
      setUserReview(
        mockReviews.find((r) => r.userId === currentUser.id) || null,
      );
    } finally {
      setReviewsLoading(false);
    }
  };

  useEffect(() => {
    fetchReviews();
  }, [attractionId]);

  const handleReviewSubmit = () => {
    setShowReviewForm(false);
    fetchReviews();
  };

  const handleReviewEdit = () => {
    setShowReviewForm(true);
  };

  const openReviewForm = () => {
    setShowReviewForm(true);
  };

  const closeReviewForm = () => {
    setShowReviewForm(false);
  };

  const handleReviewDelete = async () => {
    if (confirm("Are you sure you want to delete your review?")) {
      // Call delete API
      setUserReview(null);
      fetchReviews();
    }
  };

  const handleAskAboutReviews = () => {
    // Open chat sidebar with review context
    if (attraction) {
      const context: ChatContext = {
        type: "review-summary",
        targetType: "attraction",
        targetId: attractionId,
        attractionName: attraction.name,
      };
      chatSidebar.open(context, `Reviews for ${attraction.name}`);
    }
  };

  const handleWeatherAndTips = () => {
    if (!attraction) return;

    // Prepare the query template with attraction info
    const query = `Please help me check the weather conditions and travel tips for ${attraction.name} located in ${attraction.address.city}, ${attraction.address.country}.`;

    // Set chat context with auto-send configuration
    const context: ChatContext = {
      type: "attraction",
      targetType: "attraction",
      targetId: attractionId,
      attractionName: attraction.name,
      agent: "journey_assistant", // Route to journey_assistant agent
      autoSendQuery: query,
      autoSendMetadata: {
        agent: "journey_assistant", // This will route to journey_assistant in facade.py
      },
    };
    chatSidebar.open(context, `Weather & Tips: ${attraction.name}`);
  };

  const formatDate = (timestamp: number) => {
    return new Date(timestamp).toLocaleDateString("en-US", {
      year: "numeric",
      month: "short",
      day: "numeric",
    });
  };

  const getRatingStars = (rating: number) => {
    return Array(5)
      .fill(0)
      .map((_, i) => i < rating);
  };

  if (!attraction) {
    return null;
  }

  return (
    <div className="min-h-screen bg-gray-50">
      {/* Back button */}
      <div className="border-b border-gray-200 bg-white">
        <div className="mx-auto max-w-7xl px-4 py-4 sm:px-6 lg:px-8">
          <Link
            href="/attractions"
            className="inline-flex items-center gap-2 text-gray-600 transition-colors hover:text-gray-900"
          >
            <ChevronLeft className="h-5 w-5" />
            Back to Attractions
          </Link>
        </div>
      </div>

      {/* Main content */}
      <div className="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8">
        <div className="grid gap-8 lg:grid-cols-3">
          {/* Left column - Main content */}
          <div className="space-y-6 lg:col-span-2">
            {/* Image gallery */}
            <div className="overflow-hidden rounded-xl bg-white shadow-sm">
              <div className="relative aspect-video">
                <img
                  src={attraction.images?.[selectedImageIndex]}
                  alt={attraction.name}
                  className="h-full w-full object-cover"
                />
              </div>
              {attraction.images && attraction.images.length > 1 && (
                <div className="p-4">
                  <div className="flex gap-2 overflow-x-auto">
                    {attraction.images.map((image, index) => (
                      <button
                        key={index}
                        className={`h-20 w-20 shrink-0 overflow-hidden rounded-lg border-2 transition-all ${
                          selectedImageIndex === index
                            ? "border-primary-600 ring-primary-600/20 ring-2"
                            : "border-gray-200 hover:border-gray-300"
                        }`}
                        onClick={() => setSelectedImageIndex(index)}
                      >
                        <img
                          src={image}
                          alt={`${attraction.name} - Image ${index + 1}`}
                          className="h-full w-full object-cover"
                        />
                      </button>
                    ))}
                  </div>
                </div>
              )}
            </div>

            {/* Basic info */}
            <div className="rounded-xl bg-white p-6 shadow-sm">
              <div className="mb-4 flex items-start justify-between">
                <div>
                  <div className="mb-2 flex items-center gap-2">
                    <Badge variant="default">{attraction.category}</Badge>
                    {attraction.tags && (
                      <div className="flex gap-2">
                        {attraction.tags.slice(0, 3).map((tag) => (
                          <Badge key={tag} variant="secondary">
                            {tag}
                          </Badge>
                        ))}
                      </div>
                    )}
                  </div>
                  <h1 className="mb-2 text-3xl font-bold text-gray-900">
                    {attraction.name}
                  </h1>
                  <div className="flex items-center gap-4 text-sm text-gray-600">
                    <div className="flex items-center gap-1">
                      <MapPin className="h-4 w-4" />
                      {attraction.address.city}, {attraction.address.country}
                    </div>
                    {attraction.rating && (
                      <div className="flex items-center gap-1 text-amber-500">
                        <Star className="h-4 w-4 fill-current" />
                        <span className="font-medium text-gray-900">
                          {attraction.rating}
                        </span>
                      </div>
                    )}
                  </div>
                </div>
                <div className="flex gap-2">
                  <button
                    className="flex h-10 w-10 items-center justify-center rounded-full bg-gray-100 text-gray-600 transition-colors hover:bg-gray-200"
                    title="Share"
                  >
                    <Share2 className="h-5 w-5" />
                  </button>
                  <button
                    className="flex h-10 w-10 items-center justify-center rounded-full bg-gray-100 text-gray-600 transition-colors hover:bg-red-50 hover:text-red-500"
                    title="Add to favorites"
                  >
                    <Heart className="h-5 w-5" />
                  </button>
                </div>
              </div>

              <div className="border-t border-gray-100 pt-4">
                <h2 className="mb-3 text-lg font-semibold text-gray-900">
                  About
                </h2>
                <p className="leading-relaxed text-gray-600">
                  {attraction.description}
                </p>
              </div>

              <div className="mt-6 border-t border-gray-100 pt-6">
                <h2 className="mb-4 text-lg font-semibold text-gray-900">
                  Address
                </h2>
                <p className="text-gray-600">
                  {attraction.address.street}
                  <br />
                  {attraction.address.county}, {attraction.address.city}
                  <br />
                  {attraction.address.province}, {attraction.address.country}
                </p>
              </div>
            </div>

            {/* Reviews Section */}
            <div id="reviews" className="rounded-xl bg-white p-6 shadow-sm">
              <div className="mb-6 flex items-center justify-between">
                <h2 className="text-2xl font-bold text-gray-900">Reviews</h2>
                <div className="flex gap-3">
                  <Button variant="outline" onClick={handleAskAboutReviews}>
                    <MessageCircle className="mr-2 h-4 w-4" />
                    Ask About Reviews
                  </Button>
                  {!userReview && (
                    <Button variant="default" onClick={openReviewForm}>
                      Write a Review
                    </Button>
                  )}
                </div>
              </div>

              {/* Review Form */}
              {showReviewForm && (
                <div className="mb-6">
                  <ReviewForm
                    attractionId={attractionId}
                    userId={currentUser.id}
                    existingReview={userReview}
                    onSubmit={handleReviewSubmit}
                    onCancel={closeReviewForm}
                  />
                </div>
              )}

              {/* User's own review (shown at top) */}
              {userReview && !showReviewForm && (
                <div className="mb-6">
                  <div className="rounded-lg border border-blue-200 bg-blue-50 p-4">
                    <div className="mb-3 flex items-start justify-between">
                      <div>
                        <div className="mb-1 flex items-center gap-2">
                          <span className="font-semibold text-gray-900">
                            Your Review
                          </span>
                          <div className="flex gap-0.5">
                            {getRatingStars(userReview.rating).map(
                              (filled, index) => (
                                <Star
                                  key={index}
                                  className={`h-4 w-4 ${filled ? "fill-current text-amber-400" : "text-gray-300"}`}
                                />
                              ),
                            )}
                          </div>
                        </div>
                        <p className="text-sm text-gray-500">
                          {formatDate(userReview.createdAt)}
                        </p>
                      </div>
                      <div className="flex gap-2">
                        <Button
                          variant="ghost"
                          size="sm"
                          onClick={handleReviewEdit}
                        >
                          Edit
                        </Button>
                        <Button
                          variant="ghost"
                          size="sm"
                          onClick={handleReviewDelete}
                        >
                          Delete
                        </Button>
                      </div>
                    </div>
                    <p className="mb-3 text-gray-700">{userReview.text}</p>
                    {userReview.images.length > 0 && (
                      <div className="flex flex-wrap gap-2">
                        {userReview.images.map((image, index) => (
                          <img
                            key={index}
                            src={image}
                            alt={`Review image ${index + 1}`}
                            className="h-24 w-24 rounded-lg object-cover"
                          />
                        ))}
                      </div>
                    )}
                  </div>
                </div>
              )}

              {/* Other reviews */}
              {reviewsLoading ? (
                <div className="py-8 text-center">
                  <p className="text-gray-500">Loading reviews...</p>
                </div>
              ) : reviews.length === 0 ? (
                <div className="py-8 text-center">
                  <p className="text-gray-500">
                    No reviews yet. Be the first to review!
                  </p>
                </div>
              ) : (
                <div className="space-y-6">
                  {reviews
                    .filter((r) => r.userId !== currentUser.id)
                    .map((review) => (
                      <div
                        key={review.id}
                        className="border-b border-gray-100 pb-6 last:border-0"
                      >
                        <div className="flex items-start gap-4">
                          <div className="flex h-10 w-10 items-center justify-center rounded-full bg-gray-200">
                            <span className="text-sm font-medium text-gray-600">
                              U
                            </span>
                          </div>
                          <div className="flex-1">
                            <div className="mb-1 flex items-center gap-2">
                              <span className="font-semibold text-gray-900">
                                User {review.userId.slice(-1)}
                              </span>
                              <div className="flex gap-0.5">
                                {getRatingStars(review.rating).map(
                                  (filled, index) => (
                                    <Star
                                      key={index}
                                      className={`h-4 w-4 ${filled ? "fill-current text-amber-400" : "text-gray-300"}`}
                                    />
                                  ),
                                )}
                              </div>
                            </div>
                            <p className="mb-3 text-sm text-gray-500">
                              {formatDate(review.createdAt)}
                            </p>
                            <p className="mb-3 text-gray-700">{review.text}</p>
                            {review.images.length > 0 && (
                              <div className="flex flex-wrap gap-2">
                                {review.images.map((image, index) => (
                                  <img
                                    key={index}
                                    src={image}
                                    alt={`Review image ${index + 1}`}
                                    className="h-24 w-24 rounded-lg object-cover"
                                  />
                                ))}
                              </div>
                            )}
                          </div>
                        </div>
                      </div>
                    ))}
                </div>
              )}
            </div>
          </div>

          {/* Right column - Sidebar info */}
          <div className="lg:col-span-1">
            <div className="sticky top-22 rounded-xl bg-white p-6 shadow-sm">
              <h3 className="mb-4 text-lg font-semibold text-gray-900">
                Visit Information
              </h3>

              <div className="space-y-4">
                <div className="flex items-start gap-3">
                  <Clock className="mt-0.5 h-5 w-5 text-gray-400" />
                  <div>
                    <p className="font-medium text-gray-900">Opening Hours</p>
                    <p className="text-sm text-gray-600">
                      {attraction.openingHours}
                    </p>
                  </div>
                </div>

                <div className="flex items-start gap-3">
                  <Ticket className="mt-0.5 h-5 w-5 text-gray-400" />
                  <div>
                    <p className="font-medium text-gray-900">Ticket Price</p>
                    <p className="text-sm text-gray-600">
                      {attraction.ticketPrice}
                    </p>
                  </div>
                </div>

                <div className="flex items-start gap-3">
                  <MapPin className="mt-0.5 h-5 w-5 text-gray-400" />
                  <div>
                    <p className="font-medium text-gray-900">Location</p>
                    <p className="text-sm text-gray-600">
                      {attraction.location.lat.toFixed(4)},{" "}
                      {attraction.location.lng.toFixed(4)}
                    </p>
                  </div>
                </div>

                <div
                  onClick={handleWeatherAndTips}
                  className="-mx-3 flex cursor-pointer items-start gap-3 rounded-lg px-3 py-2 transition-colors hover:bg-gray-50"
                >
                  <Cloud className="mt-0.5 h-5 w-5 text-gray-400" />
                  <div>
                    <p className="font-medium text-gray-900">Weather & Tips</p>
                    <p className="text-sm text-gray-600">
                      Check weather and travel tips
                    </p>
                  </div>
                </div>
              </div>

              <div className="mt-6 border-t border-gray-100 pt-6">
                <Button variant="default" className="w-full">
                  Get Directions
                </Button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

// trip-web-frontend/app/pages/attractions/[id].vue
<script setup lang="ts">
import { MapPin, Star, Clock, Ticket, ChevronLeft, Share2, Heart, MessageCircle, Cloud } from 'lucide-vue-next'
import ReviewForm from '~/components/reviews/ReviewForm.vue'
import ChatSidebar from '~/components/chat/ChatSidebar.vue'
import type { Attraction, Review, ChatContext } from '~/types'

definePageMeta({
  layout: 'default',
})

const route = useRoute()
const attractionId = route.params.id as string
// TODO: Replace with real authentication when user service is integrated
const currentUser = ref({ id: 'user-1', username: 'Demo User' })

// Chat sidebar state
const isChatSidebarOpen = ref(false)
const chatContext = ref<ChatContext | null>(null)
const chatTitle = ref('AI Assistant')

// Mock attraction data (in production, this would be fetched from the API)
const attraction = ref<Attraction>({
  id: attractionId,
  name: 'The Bund',
  description: 'The Bund is a waterfront area in central Shanghai, featuring a mix of historical colonial-era buildings and modern skyscrapers. It offers stunning views of the Huangpu River and the futuristic Pudong skyline across the water. A must-visit destination for any traveler to Shanghai, the Bund combines history, architecture, and vibrant city life.',
  address: { 
    country: 'China', 
    province: 'Shanghai', 
    city: 'Shanghai', 
    county: 'Huangpu', 
    district: '', 
    street: 'Zhongshan East 1st Road' 
  },
  location: { lng: 121.4883, lat: 31.2319 },
  category: 'Landmark',
  rating: 4.8,
  openingHours: '24 hours',
  ticketPrice: 'Free',
  images: [
    'https://images.unsplash.com/photo-1474181487882-5abf3f0ba6c2?w=1200&h=800&fit=crop',
    'https://images.unsplash.com/photo-1548919973-5cef591cdbc9?w=1200&h=800&fit=crop',
    'https://images.unsplash.com/photo-1538428494232-9c0d8a3ab403?w=1200&h=800&fit=crop',
  ],
  tags: ['Historic', 'Scenic', 'Night View', 'Photography'],
})

const selectedImageIndex = ref(0)
const showReviewForm = ref(false)
const reviews = ref<Review[]>([])
const reviewsLoading = ref(false)
const userReview = ref<Review | null>(null)

// Fetch reviews
const fetchReviews = async () => {
  reviewsLoading.value = true
  try {
    // This would call the actual API
    // const response = await fetch(`${runtimeConfig.public.reviewServiceUrl}/reviews?targetType=attraction&targetId=${attractionId}`)
    // For now, using mock data
    await new Promise(resolve => setTimeout(resolve, 500))
    
    // Mock reviews data
    const mockReviews: Review[] = [
      {
        id: 'review-1',
        userId: 'user-2',
        targetType: 'attraction',
        targetId: attractionId,
        rating: 5,
        text: 'Absolutely stunning views, especially at night! The historic buildings are beautifully preserved and the modern skyline across the river is breathtaking.',
        images: ['https://images.unsplash.com/photo-1474181487882-5abf3f0ba6c2?w=400&h=300&fit=crop'],
        createdAt: Date.now() - 86400000 * 2,
        updatedAt: Date.now() - 86400000 * 2,
      },
      {
        id: 'review-2',
        userId: 'user-3',
        targetType: 'attraction',
        targetId: attractionId,
        rating: 4,
        text: 'Great place for a walk along the waterfront. Very crowded during weekends and holidays though.',
        images: [],
        createdAt: Date.now() - 86400000 * 5,
        updatedAt: Date.now() - 86400000 * 5,
      },
      {
        id: 'review-3',
        userId: 'user-4',
        targetType: 'attraction',
        targetId: attractionId,
        rating: 5,
        text: 'Perfect spot for photography! Visited during sunset and the golden hour lighting was amazing.',
        images: [
          'https://images.unsplash.com/photo-1548919973-5cef591cdbc9?w=400&h=300&fit=crop',
          'https://images.unsplash.com/photo-1538428494232-9c0d8a3ab403?w=400&h=300&fit=crop'
        ],
        createdAt: Date.now() - 86400000 * 7,
        updatedAt: Date.now() - 86400000 * 7,
      },
    ]
    
    reviews.value = mockReviews
    
    // Check if current user has reviewed
    userReview.value = mockReviews.find(r => r.userId === currentUser.value.id) || null
  } finally {
    reviewsLoading.value = false
  }
}

const handleReviewSubmit = () => {
  showReviewForm.value = false
  fetchReviews()
}

const handleReviewEdit = () => {
  showReviewForm.value = true
}

const openReviewForm = () => {
  showReviewForm.value = true
}

const closeReviewForm = () => {
  showReviewForm.value = false
}

const handleReviewDelete = async () => {
  if (confirm('Are you sure you want to delete your review?')) {
    // Call delete API
    userReview.value = null
    fetchReviews()
  }
}

const handleAskAboutReviews = () => {
  // Open chat sidebar with review context
  chatContext.value = {
    type: 'review-summary',
    targetType: 'attraction',
    targetId: attractionId,
    attractionName: attraction.value.name,
  }
  chatTitle.value = `Reviews for ${attraction.value.name}`
  isChatSidebarOpen.value = true
}

// Weather & Tips - Auto-send query with journey_assistant agent
const handleWeatherAndTips = () => {
  // Prepare the query template with attraction info
  const query = `Please help me check the weather conditions and travel tips for ${attraction.value.name} located in ${attraction.value.address.city}, ${attraction.value.address.country}.`
  
  // Set chat context with auto-send configuration
  chatContext.value = {
    type: 'attraction',
    targetType: 'attraction',
    targetId: attractionId,
    attractionName: attraction.value.name,
    agent: 'journey_assistant', // Route to journey_assistant agent
    autoSendQuery: query,
    autoSendMetadata: {
      agent: 'journey_assistant', // This will route to journey_assistant in facade.py
    },
  }
  chatTitle.value = `Weather & Tips: ${attraction.value.name}`
  isChatSidebarOpen.value = true
}

const closeChatSidebar = () => {
  isChatSidebarOpen.value = false
  // Reset chat context to allow creating a new conversation next time
  chatContext.value = null
}

onMounted(() => {
  fetchReviews()
})

const formatDate = (timestamp: number) => {
  return new Date(timestamp).toLocaleDateString('en-US', { 
    year: 'numeric', 
    month: 'short', 
    day: 'numeric' 
  })
}

const getRatingStars = (rating: number) => {
  return Array(5).fill(0).map((_, i) => i < rating)
}
</script>

<template>
  <div class="min-h-screen bg-gray-50">
    <!-- Back button -->
    <div class="bg-white border-b border-gray-200">
      <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-4">
        <NuxtLink 
          to="/attractions" 
          class="inline-flex items-center gap-2 text-gray-600 hover:text-gray-900 transition-colors"
        >
          <ChevronLeft class="w-5 h-5" />
          Back to Attractions
        </NuxtLink>
      </div>
    </div>

    <!-- Main content -->
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
      <div class="grid lg:grid-cols-3 gap-8">
        <!-- Left column - Main content -->
        <div class="lg:col-span-2 space-y-6">
          <!-- Image gallery -->
          <div class="bg-white rounded-xl shadow-sm overflow-hidden">
            <div class="aspect-[16/9] relative">
              <img
                :src="attraction.images?.[selectedImageIndex]"
                :alt="attraction.name"
                class="w-full h-full object-cover"
              />
            </div>
            <div v-if="attraction.images && attraction.images.length > 1" class="p-4">
              <div class="flex gap-2 overflow-x-auto">
                <button
                  v-for="(image, index) in attraction.images"
                  :key="index"
                  :class="[
                    'flex-shrink-0 w-20 h-20 rounded-lg overflow-hidden border-2 transition-all',
                    selectedImageIndex === index
                      ? 'border-primary-600 ring-2 ring-primary-600/20'
                      : 'border-gray-200 hover:border-gray-300'
                  ]"
                  @click="selectedImageIndex = index"
                >
                  <img
                    :src="image"
                    :alt="`${attraction.name} - Image ${index + 1}`"
                    class="w-full h-full object-cover"
                  />
                </button>
              </div>
            </div>
          </div>

          <!-- Basic info -->
          <div class="bg-white rounded-xl shadow-sm p-6">
            <div class="flex items-start justify-between mb-4">
              <div>
                <div class="flex items-center gap-2 mb-2">
                  <UiBadge variant="default" size="md">
                    {{ attraction.category }}
                  </UiBadge>
                  <div v-if="attraction.tags" class="flex gap-2">
                    <UiBadge
                      v-for="tag in attraction.tags.slice(0, 3)"
                      :key="tag"
                      variant="secondary"
                      size="sm"
                    >
                      {{ tag }}
                    </UiBadge>
                  </div>
                </div>
                <div class="flex items-center gap-3 mb-2">
                  <h1 class="text-3xl font-bold text-gray-900">
                    {{ attraction.name }}
                  </h1>
                  <UiButton
                    variant="outline"
                    size="sm"
                    @click="handleWeatherAndTips"
                    class="flex items-center gap-2"
                  >
                    <Cloud class="w-4 h-4" />
                    Weather & Tips
                  </UiButton>
                </div>
                <div class="flex items-center gap-4 text-sm text-gray-600">
                  <div class="flex items-center gap-1">
                    <MapPin class="w-4 h-4" />
                    {{ attraction.address.city }}, {{ attraction.address.country }}
                  </div>
                  <div v-if="attraction.rating" class="flex items-center gap-1 text-amber-500">
                    <Star class="w-4 h-4 fill-current" />
                    <span class="font-medium text-gray-900">{{ attraction.rating }}</span>
                  </div>
                </div>
              </div>
              <div class="flex gap-2">
                <button
                  class="w-10 h-10 rounded-full bg-gray-100 hover:bg-gray-200 flex items-center justify-center text-gray-600 transition-colors"
                  title="Share"
                >
                  <Share2 class="w-5 h-5" />
                </button>
                <button
                  class="w-10 h-10 rounded-full bg-gray-100 hover:bg-red-50 flex items-center justify-center text-gray-600 hover:text-red-500 transition-colors"
                  title="Add to favorites"
                >
                  <Heart class="w-5 h-5" />
                </button>
              </div>
            </div>

            <div class="border-t border-gray-100 pt-4">
              <h2 class="text-lg font-semibold text-gray-900 mb-3">About</h2>
              <p class="text-gray-600 leading-relaxed">
                {{ attraction.description }}
              </p>
            </div>

            <div class="border-t border-gray-100 mt-6 pt-6">
              <h2 class="text-lg font-semibold text-gray-900 mb-4">Address</h2>
              <p class="text-gray-600">
                {{ attraction.address.street }}<br>
                {{ attraction.address.county }}, {{ attraction.address.city }}<br>
                {{ attraction.address.province }}, {{ attraction.address.country }}
              </p>
            </div>
          </div>

          <!-- Reviews Section -->
          <div id="reviews" class="bg-white rounded-xl shadow-sm p-6">
            <div class="flex items-center justify-between mb-6">
              <h2 class="text-2xl font-bold text-gray-900">Reviews</h2>
              <div class="flex gap-3">
                <UiButton
                  variant="outline"
                  size="sm"
                  @click="handleAskAboutReviews"
                >
                  <MessageCircle class="w-4 h-4 mr-2" />
                  Ask About Reviews
                </UiButton>
                <UiButton
                  v-if="!userReview"
                  variant="primary"
                  size="sm"
                  @click="openReviewForm"
                >
                  Write a Review
                </UiButton>
              </div>
            </div>

            <!-- Review Form -->
            <div v-if="showReviewForm" class="mb-6">
              <ReviewForm
                :attraction-id="attractionId"
                :user-id="currentUser.id"
                :existing-review="userReview"
                @submit="handleReviewSubmit"
                @cancel="closeReviewForm"
              />
            </div>

            <!-- User's own review (shown at top) -->
            <div v-if="userReview && !showReviewForm" class="mb-6">
              <div class="bg-blue-50 border border-blue-200 rounded-lg p-4">
                <div class="flex items-start justify-between mb-3">
                  <div>
                    <div class="flex items-center gap-2 mb-1">
                      <span class="font-semibold text-gray-900">Your Review</span>
                      <div class="flex gap-0.5">
                        <Star
                          v-for="(filled, index) in getRatingStars(userReview.rating)"
                          :key="index"
                          :class="['w-4 h-4', filled ? 'text-amber-400 fill-current' : 'text-gray-300']"
                        />
                      </div>
                    </div>
                    <p class="text-sm text-gray-500">{{ formatDate(userReview.createdAt) }}</p>
                  </div>
                  <div class="flex gap-2">
                    <UiButton variant="ghost" size="sm" @click="handleReviewEdit">
                      Edit
                    </UiButton>
                    <UiButton variant="ghost" size="sm" @click="handleReviewDelete">
                      Delete
                    </UiButton>
                  </div>
                </div>
                <p class="text-gray-700 mb-3">{{ userReview.text }}</p>
                <div v-if="userReview.images.length > 0" class="flex gap-2 flex-wrap">
                  <img
                    v-for="(image, index) in userReview.images"
                    :key="index"
                    :src="image"
                    :alt="`Review image ${index + 1}`"
                    class="w-24 h-24 object-cover rounded-lg"
                  />
                </div>
              </div>
            </div>

            <!-- Other reviews -->
            <div v-if="reviewsLoading" class="text-center py-8">
              <p class="text-gray-500">Loading reviews...</p>
            </div>
            <div v-else-if="reviews.length === 0" class="text-center py-8">
              <p class="text-gray-500">No reviews yet. Be the first to review!</p>
            </div>
            <div v-else class="space-y-6">
              <div
                v-for="review in reviews.filter(r => r.userId !== currentUser.id)"
                :key="review.id"
                class="border-b border-gray-100 pb-6 last:border-0"
              >
                <div class="flex items-start gap-4">
                  <div class="w-10 h-10 rounded-full bg-gray-200 flex items-center justify-center">
                    <span class="text-sm font-medium text-gray-600">U</span>
                  </div>
                  <div class="flex-1">
                    <div class="flex items-center gap-2 mb-1">
                      <span class="font-semibold text-gray-900">User {{ review.userId.slice(-1) }}</span>
                      <div class="flex gap-0.5">
                        <Star
                          v-for="(filled, index) in getRatingStars(review.rating)"
                          :key="index"
                          :class="['w-4 h-4', filled ? 'text-amber-400 fill-current' : 'text-gray-300']"
                        />
                      </div>
                    </div>
                    <p class="text-sm text-gray-500 mb-3">{{ formatDate(review.createdAt) }}</p>
                    <p class="text-gray-700 mb-3">{{ review.text }}</p>
                    <div v-if="review.images.length > 0" class="flex gap-2 flex-wrap">
                      <img
                        v-for="(image, index) in review.images"
                        :key="index"
                        :src="image"
                        :alt="`Review image ${index + 1}`"
                        class="w-24 h-24 object-cover rounded-lg"
                      />
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

        <!-- Right column - Sidebar info -->
        <div class="lg:col-span-1">
          <div class="bg-white rounded-xl shadow-sm p-6 sticky top-8">
            <h3 class="text-lg font-semibold text-gray-900 mb-4">Visit Information</h3>
            
            <div class="space-y-4">
              <div class="flex items-start gap-3">
                <Clock class="w-5 h-5 text-gray-400 mt-0.5" />
                <div>
                  <p class="font-medium text-gray-900">Opening Hours</p>
                  <p class="text-sm text-gray-600">{{ attraction.openingHours }}</p>
                </div>
              </div>

              <div class="flex items-start gap-3">
                <Ticket class="w-5 h-5 text-gray-400 mt-0.5" />
                <div>
                  <p class="font-medium text-gray-900">Ticket Price</p>
                  <p class="text-sm text-gray-600">{{ attraction.ticketPrice }}</p>
                </div>
              </div>

              <div class="flex items-start gap-3">
                <MapPin class="w-5 h-5 text-gray-400 mt-0.5" />
                <div>
                  <p class="font-medium text-gray-900">Location</p>
                  <p class="text-sm text-gray-600">
                    {{ attraction.location.lat.toFixed(4) }}, {{ attraction.location.lng.toFixed(4) }}
                  </p>
                </div>
              </div>
            </div>

            <div class="mt-6 pt-6 border-t border-gray-100">
              <UiButton variant="primary" class="w-full">
                Get Directions
              </UiButton>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- Chat Sidebar -->
    <ChatSidebar
      :is-open="isChatSidebarOpen"
      :initial-context="chatContext"
      :title="chatTitle"
      @close="closeChatSidebar"
    />
  </div>
</template>
